service: project-01
frameworkVersion: '3'

custom:
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev


plugins:
  - serverless-offline

functions:
  graphql:
    handler: handler.graphqlHandler
    events:
    - http:
        path: /graphql
        method: post
        cors: true
    - http:
        path: /graphql
        method: get
        cors: true

